---
language: python

os: linux
dist: bionic

before_script:
  - pip install -U pip
  - pip install -r requirements.txt

script:
  - ansible-playbook -i inventory/inventory pb.batfish.validate_facts.yml
