interfaces:
  - name: "GigabitEthernet0/0"
    ip_address: "67.128.128.2/24"
    nameif: "outside"
    security_level: 0
  - name: "GigabitEthernet2"
    ip_address: "10.255.255.5/31"
    nameif: "inside"
    security_level: 100
  - name: "Management0/0"
