interfaces:
  - name: "Loopback0"
    enabled: True
  - name: "Loopback1"
    enabled: True
    ip_address: "192.168.100.1/32"
  - name: "GigabitEthernet0/0"
  - name: "GigabitEthernet0/1"
    enabled: True
    description: "to GigabitEthernet0/1.fw-1"
    ip_address: "10.255.255.6/30"
  - name: "GigabitEthernet0/2"
    enabled: True
    description: "to GigabitEthernet0/1.core-2"
    ip_address: "10.255.255.9/30"
  - name: "GigabitEthernet0/3"
    enabled: True
    description: "to GigabitEthernet0/1.core-3"
    ip_address: "10.255.255.13/30"
