---
ospf:
  default_info_orig: True
  process: 10
  networks:
    - ip_network: "192.168.100.1/32"
      area: 0
    - ip_network: "10.255.255.12/30"
      area: 0
    - ip_network: "10.255.255.8/30"
      area: 0
